[package]
name = "topcat"
version = "0.2.4"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = ["josha@jci.dev", ]

description = "A tool for concatenating files in topological order"
documentation = "https://docs.rs/topcat/"
repository = "https://github.com/joshainglis/topcat"

keywords = ["topological", "concatenation", "file", "dependency", "graph"]
categories = [
    "command-line-utilities",
    "development-tools",
    "filesystem",
    "template-engine",
]

rust-version = "1.88.0"
edition = "2024"

[package.metadata.release]
no-dev-version = true

[profile.release]

[profile.bench]
debug = true

[dependencies]
petgraph = { version = "0.8.3" }
glob = { version = "0.3.3" }
structopt = { version = "0.3.26" }
log = { version = "0.4.28" }
env_logger = { version = "0.11.8" }
graph-cycles = { version = "0.3.0" }

[dev-dependencies]
tempfile = { version = "3.23.0" }
